// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nreventexporter")
	ScopeName = "github.com/jwang25/nreventexporter"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
