// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nreventexporter")
	ScopeName = "github.com/xero-internal/observability-pipeline-otel-endpoint/exporter/nreventexporter"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
